import { Icons } from "@/components/icons";
import type { Product } from "./types";

// Using placeholder images from Unsplash for demo purposes
const PLACEHOLDER = "https://images.unsplash.com/photo-";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    brand: "Apple",
    name: "iPhone 13",
    title: "iPhone 13 Midnight 128GB",
    imageUrl: `${PLACEHOLDER}1632516723866-a3ef4ae9823c?w=400&h=400&fit=crop&q=80`,
    price: 380700,
    originalPrice: 1205900,
    savingsPercent: 68,
    rating: 4.82,
    reviewCount: 1223,
    colors: [
      { name: "Midnight", hex: "#1C1C1E" },
      { name: "Starlight", hex: "#F5F0E8" },
      { name: "Blue", hex: "#397CA8" },
      { name: "Pink", hex: "#FADADB" },
      { name: "Red", hex: "#BF2032" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    condition: "UK Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["iPhone 14", "Google Pixel 7", "Samsung Galaxy S22"],
    badge: "sale",
    category: "iPhone",
    seller: {
      id: "s1",
      username: "techvault_ng",
      rating: 4.9,
      verified: true,
      totalSales: 312,
    },
    listedAgo: "2 days ago",
    specs: {
      Brand: "Apple",
      Model: "iPhone 13",
      Series: "iPhone 13",
      "Screen Size": "6.1 inches",
      "Screen Type": "Super Retina XDR OLED",
      Storage: "128GB",
      Color: "Midnight",
      "Release Date": "2021",
      "5G": "Yes",
      Connector: "Lightning",
      Unlocked: "Yes",
    },
  },
  {
    id: "p2",
    brand: "Apple",
    name: "iPhone 16 Pro Max",
    title: "iPhone 16 Pro Max 256GB Natural Titanium",
    imageUrl: `${PLACEHOLDER}1695048133547-9bc356ee6b74?w=400&h=400&fit=crop&q=80`,
    price: 1150000,
    originalPrice: 1499000,
    savingsPercent: 23,
    rating: 4.95,
    reviewCount: 89,
    colors: [
      { name: "Natural Titanium", hex: "#C4B9A9" },
      { name: "Black Titanium", hex: "#3D3935" },
      { name: "White Titanium", hex: "#F2EFE9" },
      { name: "Desert Titanium", hex: "#B89A7A" },
    ],
    storage: ["256GB", "512GB", "1TB"],
    condition: "UK Used",
    mode: "buy",
    swapStatus: "none",
    badge: "new",
    category: "iPhone",
    seller: {
      id: "s2",
      username: "gadget_plug",
      rating: 4.7,
      verified: true,
      totalSales: 88,
    },
    listedAgo: "5 hours ago",
    specs: {
      Brand: "Apple",
      Model: "iPhone 16 Pro Max",
      Series: "iPhone 16",
      "Screen Size": "6.9 inches",
      "Screen Type": "Super Retina XDR ProMotion OLED",
      Storage: "256GB",
      Color: "Natural Titanium",
      "Release Date": "2024",
      "5G": "Yes",
      Connector: "USB-C",
      Unlocked: "Yes",
    },
  },
  {
    id: "p3",
    brand: "Samsung",
    name: "Galaxy S24 Ultra",
    title: "Samsung Galaxy S24 Ultra 256GB Titanium Black",
    imageUrl: `${PLACEHOLDER}1610945415114-a0c758a4ab96?w=400&h=400&fit=crop&q=80`,
    price: 675000,
    originalPrice: 950000,
    savingsPercent: 29,
    rating: 4.7,
    reviewCount: 341,
    colors: [
      { name: "Titanium Black", hex: "#1C1C1C" },
      { name: "Titanium Gray", hex: "#7A7A7A" },
      { name: "Titanium Violet", hex: "#6B5B7B" },
      { name: "Titanium Yellow", hex: "#C8A84B" },
    ],
    storage: ["256GB", "512GB", "1TB"],
    condition: "UK Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["iPhone 15", "Galaxy S23 Ultra"],
    badge: "sale",
    category: "Android",
    seller: {
      id: "s3",
      username: "phones_warehouse",
      rating: 4.6,
      verified: true,
      totalSales: 450,
    },
    listedAgo: "1 day ago",
    specs: {
      Brand: "Samsung",
      Model: "Galaxy S24 Ultra",
      "Screen Size": "6.8 inches",
      "Screen Type": "Dynamic AMOLED 2X",
      Storage: "256GB",
      Color: "Titanium Black",
      "Release Date": "2024",
      "5G": "Yes",
      Connector: "USB-C",
      Unlocked: "Yes",
    },
  },
  {
    id: "p4",
    brand: "Apple",
    name: "MacBook Pro 14",
    title: "MacBook Pro 14-inch M3 Pro 512GB Space Black",
    imageUrl: `${PLACEHOLDER}1517336714731-489689fd1ca8?w=400&h=400&fit=crop&q=80`,
    price: 1350000,
    originalPrice: 1850000,
    savingsPercent: 27,
    rating: 4.9,
    reviewCount: 167,
    colors: [
      { name: "Space Black", hex: "#2C2C2C" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    storage: ["512GB", "1TB"],
    condition: "UK Used",
    mode: "buy",
    swapStatus: "none",
    badge: "deal-of-week",
    category: "MacBook",
    seller: {
      id: "s4",
      username: "apple_hub_lagos",
      rating: 5.0,
      verified: true,
      totalSales: 156,
    },
    listedAgo: "3 days ago",
  },
  {
    id: "p5",
    brand: "Apple",
    name: "iPad Pro 12.9",
    title: "iPad Pro 12.9-inch M2 256GB Wi-Fi Space Gray",
    imageUrl: `${PLACEHOLDER}1544244015-0df4cec9d57f?w=400&h=400&fit=crop&q=80`,
    price: 485000,
    originalPrice: 680000,
    savingsPercent: 29,
    rating: 4.8,
    reviewCount: 203,
    colors: [
      { name: "Space Gray", hex: "#6B6B70" },
      { name: "Silver", hex: "#D1D1D6" },
    ],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    condition: "Nigerian Used",
    mode: "both",
    swapStatus: "pending",
    swapFor: ["MacBook Air", "iPad Pro 11"],
    badge: "sale",
    category: "iPad",
    seller: {
      id: "s5",
      username: "device_swap_ng",
      rating: 4.5,
      verified: false,
      totalSales: 42,
    },
    listedAgo: "4 hours ago",
  },
  {
    id: "p6",
    brand: "Apple",
    name: "Apple Watch Ultra 2",
    slug: "",
    title: "Apple Watch Ultra 2 GPS+Cellular 49mm Natural Titanium",
    imageUrl: `${PLACEHOLDER}1434494878577-86c23bcb06b9?w=400&h=400&fit=crop&q=80`,
    price: 520000,
    originalPrice: 750000,
    savingsPercent: 31,
    rating: 4.75,
    reviewCount: 98,
    colors: [
      { name: "Natural Titanium", hex: "#C4B9A9" },
      { name: "Black Titanium", hex: "#3D3935" },
    ],
    condition: "UK Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["Apple Watch Series 9", "Galaxy Watch 7"],
    badge: "sale",
    category: "Watches",
    seller: {
      id: "s6",
      username: "wristtech",
      rating: 4.8,
      verified: true,
      totalSales: 78,
    },
    listedAgo: "6 hours ago",
  },
  {
    id: "p7",
    brand: "Google",
    name: "Pixel 8 Pro",
    title: "Google Pixel 8 Pro 256GB Bay",
    imageUrl: `${PLACEHOLDER}1598327105854-b8c1e3fc7e49?w=400&h=400&fit=crop&q=80`,
    price: 310000,
    originalPrice: 499000,
    savingsPercent: 38,
    rating: 4.6,
    reviewCount: 412,
    colors: [
      { name: "Bay", hex: "#5B7FA6" },
      { name: "Obsidian", hex: "#1A1918" },
      { name: "Porcelain", hex: "#F0EDE6" },
    ],
    storage: ["128GB", "256GB"],
    condition: "UK Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["Pixel 7 Pro", "Samsung Galaxy S23"],
    badge: "deal-of-week",
    category: "Android",
    seller: {
      id: "s7",
      username: "google_store_ng",
      rating: 4.7,
      verified: true,
      totalSales: 203,
    },
    listedAgo: "1 day ago",
  },
  {
    id: "p8",
    brand: "Apple",
    model: "iPhone 15 Pro",
    title: "iPhone 15 Pro 256GB Black Titanium",
    imageUrl: `${PLACEHOLDER}1680663688-1d3c0cc498db?w=400&h=400&fit=crop&q=80`,
    price: 750000,
    originalPrice: 1100000,
    savingsPercent: 32,
    rating: 4.88,
    reviewCount: 567,
    colors: [
      { name: "Black Titanium", hex: "#3D3935" },
      { name: "White Titanium", hex: "#F2EFE9" },
      { name: "Blue Titanium", hex: "#4E7B8B" },
      { name: "Natural Titanium", hex: "#C4B9A9" },
    ],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    condition: "UK Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["iPhone 14 Pro", "Samsung Galaxy S24"],
    badge: "sale",
    isSoldOut: false,
    category: "iPhone",
    seller: {
      id: "s8",
      username: "prime_phones",
      rating: 4.9,
      verified: true,
      totalSales: 892,
    },
    listedAgo: "12 hours ago",
  },
  {
    id: "p9",
    brand: "Sony",
    name: "WH-1000XM5",
    slug: "",
    title: "Sony WH-1000XM5 Wireless Noise-Cancelling Headphones",
    imageUrl: `${PLACEHOLDER}1505740420928-5e560c06d30e?w=400&h=400&fit=crop&q=80`,
    price: 185000,
    originalPrice: 280000,
    savingsPercent: 34,
    rating: 4.72,
    reviewCount: 1089,
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "Silver", hex: "#E8E8E8" },
    ],
    condition: "UK Used",
    mode: "buy",
    swapStatus: "none",
    badge: "sale",
    category: "Audio",
    seller: {
      id: "s9",
      username: "audio_world_ng",
      rating: 4.6,
      verified: true,
      totalSales: 134,
    },
    listedAgo: "2 days ago",
  },
  {
    id: "p10",
    brand: "Apple",
    model: "iPhone 12 Pro",
    title: "iPhone 12 Pro 256GB Pacific Blue",
    imageUrl: `${PLACEHOLDER}1609252925116-1e5e9e1e3b71?w=400&h=400&fit=crop&q=80`,
    price: 285000,
    originalPrice: 720000,
    savingsPercent: 60,
    rating: 4.65,
    reviewCount: 2341,
    colors: [
      { name: "Pacific Blue", hex: "#006EB6" },
      { name: "Graphite", hex: "#54524F" },
      { name: "Silver", hex: "#E3E4E5" },
      { name: "Gold", hex: "#FCD9A3" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    condition: "Nigerian Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["iPhone 11 Pro", "Samsung Galaxy S21"],
    badge: "sale",
    category: "iPhone",
    seller: {
      id: "s10",
      username: "budget_tech_ng",
      rating: 4.4,
      verified: false,
      totalSales: 67,
    },
    listedAgo: "3 days ago",
  },
  {
    id: "p11",
    brand: "Apple",
    model: "iPhone 14",
    title: "iPhone 14 128GB Purple",
    imageUrl: `${PLACEHOLDER}1674502099955-cef21ad6fcf6?w=400&h=400&fit=crop&q=80`,
    price: 490000,
    originalPrice: 650000,
    savingsPercent: 25,
    rating: 4.78,
    reviewCount: 445,
    colors: [
      { name: "Purple", hex: "#9B59B6" },
      { name: "Midnight", hex: "#1C1C1E" },
      { name: "Starlight", hex: "#F5F0E8" },
      { name: "Blue", hex: "#3D6B8E" },
      { name: "Red", hex: "#BF2032" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    condition: "UK Used",
    mode: "both",
    swapStatus: "available",
    swapFor: ["iPhone 13", "Samsung Galaxy S23"],
    badge: "sale",
    category: "iPhone",
    seller: {
      id: "s11",
      username: "swappr_official",
      rating: 5.0,
      verified: true,
      totalSales: 1205,
    },
    listedAgo: "1 day ago",
  },
  {
    id: "p12",
    brand: "Samsung",
    model: "Galaxy Z Fold 5",
    title: "Samsung Galaxy Z Fold 5 256GB Cream",
    imageUrl: `${PLACEHOLDER}1601784551446-19ebb37b69b1?w=400&h=400&fit=crop&q=80`,
    price: 820000,
    isSoldOut: true,
    badge: "sold-out",
    rating: 4.82,
    reviewCount: 156,
    colors: [
      { name: "Cream", hex: "#F5F0E0" },
      { name: "Phantom Black", hex: "#1C1C1C" },
      { name: "Icy Blue", hex: "#B8D8E8" },
    ],
    storage: ["256GB", "512GB"],
    condition: "UK Used",
    mode: "buy",
    swapStatus: "none",
    category: "Android",
    seller: {
      id: "s12",
      username: "fold_nation",
      rating: 4.7,
      verified: true,
      totalSales: 38,
    },
    listedAgo: "5 days ago",
  },
  {
    id: "p13",
    brand: "Samsung",
    model: "Galaxy Z Fold 5",
    title: "Samsung Galaxy Z Fold 5 256GB Cream",
    imageUrl: `${PLACEHOLDER}1601784551446-19ebb37b69b1?w=400&h=400&fit=crop&q=80`,
    price: 820000,
    isSoldOut: true,
    badge: "sold-out",
    rating: 4.82,
    reviewCount: 156,
    colors: [
      { name: "Cream", hex: "#F5F0E0" },
      { name: "Phantom Black", hex: "#1C1C1C" },
      { name: "Icy Blue", hex: "#B8D8E8" },
    ],
    storage: ["256GB", "512GB"],
    condition: "UK Used",
    mode: "buy",
    swapStatus: "none",
    category: "Android",
    seller: {
      id: "s12",
      username: "fold_nation",
      rating: 4.7,
      verified: true,
      totalSales: 38,
    },
    listedAgo: "5 days ago",
  },
];

export const DEAL_OF_WEEK_PRODUCTS: Product[] = [
  MOCK_PRODUCTS[6], // Google Pixel 8
  MOCK_PRODUCTS[1], // iPhone 16 Pro Max
  MOCK_PRODUCTS[3], // MacBook Pro 14
  MOCK_PRODUCTS[5], // Apple Watch Ultra 2
];

export const CATEGORIES = [
  { label: "All", icon: Icons.flame, value: "all" },
  { label: "iPhone", value: "iPhone" },
  { label: "Android", value: "Android" },
  { label: "MacBook", value: "MacBook" },
  { label: "iPad", value: "iPad" },
  { label: "Watches", value: "Watches" },
  { label: "Audio", value: "Audio" },
  { label: "Accessories", value: "Accessories" },
];
