import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconDeviceMobile,
  IconUserPlus,
  IconHeart,
  IconBell,
  IconSearch,
  IconMenu2,
  IconHttpQue,
  IconBookmark,
  IconFlameFilled,
  IconShoppingCartCopy,
  IconExchange,
  IconShieldCheckFilled,
  IconHeartFilled,
  IconBookmarkFilled,
  IconStar,
  IconPackage,
  IconMail,
  IconMapPin,
} from "@tabler/icons-react";

import AppleIcon from "./apple-icon";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  phone: IconDeviceMobile,
  userPlus: IconUserPlus,
  question: IconHttpQue,
  apple: AppleIcon,
  heart: IconHeart,
  bell: IconBell,
  search: IconSearch,
  menu: IconMenu2,
  bookmark: IconBookmark,
  flame: IconFlameFilled,
  cartCopy: IconShoppingCartCopy,
  exchange: IconExchange,
  shieldCheck: IconShieldCheckFilled,
  heartFilled: IconHeartFilled,
  bookmarkFilled: IconBookmarkFilled,
  star: IconStar,
  package: IconPackage,
  mail: IconMail,
  mapPin: IconMapPin,
};
